name: CI
on: [workflow_dispatch, push]  # Manually run workflow and trigger on push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
